[server]
headless = true
enableCORS = false
enableXsrfProtection = false
address = "0.0.0.0"
maxUploadSize = 50

[browser]
gatherUsageStats = false

[theme]
primaryColor = "#D47A44"
backgroundColor = "#F8FAFC"
secondaryBackgroundColor = "#F1F5F9"
textColor = "#0F172A"
font = "sans serif"
